# Generated by Django 4.1.7 on 2023-03-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_plan_max_height_plan_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='exp_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
