# Generated by Django 4.1.7 on 2023-03-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_plan_exp_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='explink',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
